#!/usr/bin/python3

"""a function that add all the command line argument to a python list
"""
from sys import argv
save_to_json_file = __import__("5-save_to_json_file").save_to_json_file
load_from_json_file = __import__("6-load_from_json_file").load_from_json_file

def add_item(my_list=[]):
    for item in range(len(argv)):
        obj = load_from_json_file(argv[item])
        my_list.append(obj)

    save_to_json_file(obj, "add_item.json")
