#!/usr/bin/python3

"""a grandchiild class inheriting from rectangle"""

from models.rectangle import Rectangle

class Square(Rectangle):
    """class constructor"""
    def __init__(self, size, x=0, y=0, id=None):
        super().__init__(width, height, x=0, y=0, idx=None)
        self.__width = size
        self.__height = size

    def __str__(self):
        x = self.__x
        y = self.__y
        strr = "[Square] ({}) {}/{} - {}".format(self.id, x, y, size)
        print("".join(strr))
