#!/usr/bin/python3

import unittest
from models.base import Base
from models.rectangle import Rectangle
import os


class Test_Base(unittest.Testcase):
    """ class to test all objects attribute and methods in base.py"""

    def Test_obj(self):
        """
        test the type and id's in of each object
        """
        b1 = Base()
        self.assertFalse(b1, Base)
        self.assertFalse(type(b1), type(Base))
        self.assertFalse(id(b1), id(Base))

        b2 = Base()
        self.assertTrue(type(b2), type(Base))
        self.assertTrue(id(b2), id(Base))
