#!/usr/bin/python3

def no_c(my_string):
    new_string = []
    p = 0

    for k in range(len(string)):
        if string[k] == 'c' or string[k] == 'C':
            new_string = my_string[k - p] + my_string[k + 1]
            return (string[:k])
