#!/usr/bin/python3

"""A subclass Rectangle from the Nase class"""
from models.base import Base


class Rectangle(Base):
    """A derived class from class Base"""
    def __init__(self, width, height, x=0, y=0, id=None):
        """initializing class instance
        Note: we use private attribute getter/setters so that we can protect
        the attributes of the class

        Args:
            @width:horuzontal length of the rectangle
            @height:vertical length of the rectangle
            @x:x coordinate
            @y:y coordinate
            ud:identity of each class object
        """
        self.width = width
        self.height = height
        self.x = x
        self.y = y
        super().__init__(id)

    @property
    def width(self):
        return (self.__width)

    @width.setter
    def width(self, value):
        self.__width = value

    @property
    def height(self):
        return (self.__height)

    @height.setter
    def height(self, value):
        self.__height = value

    @property
    def x(self):
        return (self.__x)

    @x.setter
    def x(self, value):
        self.__x = value

    @property
    def y(self):
        return (self.__y)

    @y.setter
    def y(self, value):
        self.__y = value
