#!/usr/bin/python3

from models.rectangle import Rectangle
from models.square import Square

if __name__ == "__main__":
    r1 = Rectangle(10, 7, 2, 8)
    r2 = Rectangle(2, 4)
    rect_input = [r1, r2]

    Rectangle.save_to_file(rect_input)

    rect_output = Rectangle.load_from_file()

    for k in rect_input:
        print("[{}] {}".format(id(k), k))

    print("----")

    for k in rect_output:
        print("[{}] {}".format(id(k), k))

    print("----")
    print("----")

    s1 = Square(5)
    s2 = Square(7, 9, 1)
    sq_input = [s1, s2]

    Square.save_to_file(sq_input)

    sq_output = Square.load_from_file()

    for p in sq_input:
        print("[{}] {}".format(id(p), p))

    print("----")

    for p in sq_output:
        print("[{}] {}".format(id(p), p))
