#!/usr/bin/env bash
# Displays numbers from 1 to 100 in list format.
#   Displays "FizzBuzz" when the number is a multiple of 3 and 5.
#   Displays "Fizz" when the number is a multiple of 3.
#   Displays "Buzz" when the number is a multiple of 5.
#   Otherwise, displays the number.

list=$(seq 100)
for k in $list
do
	if [ $((k % 3)) -eq 0 ] && [ $((k % 5)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((k % 3)) -eq 0 ]
	then
		echo "Fizz"
	elif [ $((k % 5)) -eq 0 ]
	then
		echo "Buzz"
	else
		echo "$k"
	fi
done
